### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marcuth** [1Marcuth/flappy-bird#1]
# TODO

---

- [x] Setup inicial do canvas
- [x] Desenhar o Flappy Bird na tela
- [x] Game Loop
- [x] Desenhar resto do cenário
~- [ ] Adicionar tela de início~

**Comment by marcuth** [comment]
- [ ] Adicionar tela de início
